# Project information
site_name: 'FDUCSLG'
site_description: '技术分享、讨论与学习'
site_author: 'FDUCSLG'
site_url: 'https://fducslg.github.io/'
site_dir: 'docs'
docs_dir: 'content'
edit_uri: 'edit/master/content'
base_url: 'https://fducslg.github.io/'

# Repository
repo_name: 'fducslg/fducslg'
repo_url: 'https://github.com/fducslg/fducslg'

# Copyright
copyright: 'Built by <a href="http://github.com/fducslg">FDUCSLG</a> &copy; 2020'

# Configuration
theme:
  name: 'material'
  language: 'zh'
  custom_dir: 'custom/'
  favicon: 'static/assets/logo.jpeg'
  palette:
    primary: 'Black'
    accent: 'Blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo:
    icon: 'code'
  feature:
    tabs: true

# # Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/fducslg'
    - type: 'quote-left'
      link: 'https://fducslg.github.io/'
    - type: 'forum'
      link: 'https://fducslg.github.io/'

extra_css:
  - 'static/css/katex.css'
  - 'https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/katex.min.css'

extra_javascript:
  - 'static/js/katex.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/katex.min.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/contrib/auto-render.min.js'

# Google Analytics
google_analytics:
  - 'UA-149024530-1'
  - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - codehilite:
      linenums: true
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


nav:
  - 主页:
    - 欢迎: index.md
    - 通知: announcement.md
    - 入站仪式: welcome.md
  - 建设本站:
    - 索引: build/index.md
    - 如何贡献: build/contribute.md
    - Mkdocs 简介: build/mkdocs-intro.md
    - CI/CD: build/CICD.md
  - 课程学习:
    - 计算机: courses/index.md
    - 大数据: courses/index.md
    - 软工: courses/index.md
  - 技术学习:
    - 前端开发: technology/index.md
    - 后端开发: technology/index.md
    - 深度学习: technology/index.md
  - 资源分享:
    - Markdown: share/markdown.md
    - GitHub: share/github.md
    - 工具推荐:
      - 全平台: share/tools/ubiquitous.md
      - Linux: share/tools/linux.md
      - Windows: share/tools/windows.md
      - MacOS: share/tools/macos.md
  - 刷题:
    - 每周一题:
       - 第三周: oj/9-25.md
       - 第五周: oj/10-13.md

