# Project information
site_name: 'FDU-MSC 论坛'
site_description: '技术分享、讨论与学习'
site_author: 'FDU-MSC'
site_url: 'https://zfhu.ac.cn/fdu-msc'
site_dir: 'docs'
docs_dir: 'content'


# Repository
repo_name: 'ichn-hu/fdu-msc'
repo_url: 'https://github.com/ichn-hu/fdu-msc'

# Copyright
copyright: 'Built by <a href="http://github.com/fdu-msc">FDU-MSC</a> &copy; 2019'

# Configuration
theme:
  name: 'material'
  language: 'zh'
  custom_dir: 'custom/'
  favicon: '_static/assets/logo.jpeg'
  palette:
    primary: 'Indigo'
    accent: 'Blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo:
    icon: 'code'
  feature:
    tabs: true

# # Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/fdu-msc'
    - type: 'quote-left'
      link: 'https://fdu-msc.github.io'
    - type: 'forum'
      link: 'https://github.com/ichn-hu/fdu-msc'

extra_css:
  - '_static/css/katex.css'
  - 'https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/katex.min.css'

extra_javascript:
  - '_static/js/katex.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/katex.min.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/contrib/auto-render.min.js'

# Google Analytics
# google_analytics:
#   - 'UA-117404761-3'
#   - 'auto'

# Extensions
markdown_extensions:
  - admonition
  - footnotes
  - codehilite:
      linenums: true
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


nav:
  - 主页:
    - 欢迎: index.md
    - 通知: announcement.md
    - 如何贡献: contribute.md
    - Mkdocs 简介: mkdocs-intro.md
  - 资源分享:
    - Linux: share/linux.md
    - GitHub: share/github.md

