name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install mkdocs and theme
      run: |
        pip3 install mkdocs
        pip3 install mkdocs-material
    - name: Build site
      run: mkdocs build
