name: CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Show python version
      run: |
        python3 --version
        pip3 --version
    - name: Install mkdocs and theme
      run: |
        pip3 install mkdocs
        pip3 install mkdocs-material
    - name: Build site
      run: mkdocs build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.4.0
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs
